/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-09-11 08:24:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1746088531666L));
    _jspx_dependants.put("jar:file:/D:/study/code/javaProgramming/javaWebServletBackup/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SICT-portal/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098736290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Hệ thống quản lý trường SICT</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/main.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- Sidebar -->\r\n");
      out.write("            <div class=\"col-md-2 sidebar p-0\" style=\"position: fixed;\">\r\n");
      out.write("                <div class=\"text-left p-3 bg-dark\">\r\n");
      out.write("                    <div class=\"logo\">SICT<span class=\"sub\"> Portal</span></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"nav flex-column\">\r\n");
      out.write("                    <li class=\"nav-item active\">\r\n");
      out.write("                        <span class=\"active__subItem\"></span>\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"dashboard\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-tachometer-alt me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Dashboard\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"accountList\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-users me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Tài khoản người dùng\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"studentList\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-user-graduate me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Thông tin sinh viên\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"teacherList\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-chalkboard-teacher me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Thông tin giáo viên\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"classroomList\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-school me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Thông tin lớp học\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"student_classroom\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-user-plus me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Sinh viên - Lớp học\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item mt-3\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"logout\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-sign-out-alt me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Đăng xuất\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Main content -->\r\n");
      out.write("            <div class=\"col-md-10 main-content\" style=\"margin-left: 16.6667%; padding: 20px;\">\r\n");
      out.write("                <div class=\"tab-content\">\r\n");
      out.write("                    <!-- Dashboard Tab -->\r\n");
      out.write("                    <div class=\"dashboard\">\r\n");
      out.write("                        <h2 class=\"mb-4\">Dashboard</h2>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-3\">\r\n");
      out.write("                                <div class=\"card text-white mb-3\"\r\n");
      out.write("                                    style=\"background: linear-gradient(135deg, #007BFF, #00C2FF);\r\n");
      out.write("                                        box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.5); border-radius: 6px;\">\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div\r\n");
      out.write("                                            style=\"display: flex; align-items: center; justify-content: space-between;\">\r\n");
      out.write("                                            <h5 class=\"card-title\">Tài khoản người dùng</h5>\r\n");
      out.write("                                            <i class=\"fas fa-users me-2\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <p class=\"card-text display-6\"\r\n");
      out.write("                                            style=\"font-weight: bold; text-shadow: 5px 5px 3px rgba(0, 0, 0, 0.5);\">\r\n");
      out.write("                                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalAccount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-3\">\r\n");
      out.write("                                <div class=\"card text-white mb-3\"\r\n");
      out.write("                                    style=\"background: linear-gradient(135deg, #00b09b, #96c93d);\r\n");
      out.write("                                        box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.5); border-radius: 6px;\">\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div\r\n");
      out.write("                                            style=\"display: flex; align-items: center; justify-content: space-between;\">\r\n");
      out.write("                                            <h5 class=\"card-title\">Sinh viên</h5>\r\n");
      out.write("                                            <i class=\"fas fa-user-graduate me-2\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <p class=\"card-text display-6\"\r\n");
      out.write("                                            style=\"font-weight: bold; text-shadow: 5px 5px 3px rgba(0, 0, 0, 0.5);\">\r\n");
      out.write("                                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalStudent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-3\">\r\n");
      out.write("                                <div class=\"card text-white mb-3\"\r\n");
      out.write("                                    style=\"background: linear-gradient(135deg, #00C9FF, #92FE9D);\r\n");
      out.write("                                        box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.5); border-radius: 6px;\">\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div\r\n");
      out.write("                                            style=\"display: flex; align-items: center; justify-content: space-between;\">\r\n");
      out.write("                                            <h5 class=\"card-title\">Giáo viên</h5>\r\n");
      out.write("                                            <i class=\"fas fa-chalkboard-teacher me-2\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <p class=\"card-text display-6\"\r\n");
      out.write("                                            style=\"font-weight: bold; text-shadow: 5px 5px 3px rgba(0, 0, 0, 0.5);\">\r\n");
      out.write("                                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalTeacher}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-3\">\r\n");
      out.write("                                <div class=\"card text-white mb-3\"\r\n");
      out.write("                                    style=\"background: linear-gradient(135deg, #f7971e, #ffd200);\r\n");
      out.write("                                        box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.5); border-radius: 6px;\">\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div\r\n");
      out.write("                                            style=\"display: flex; align-items: center; justify-content: space-between;\">\r\n");
      out.write("                                            <h5 class=\"card-title\">Lớp học</h5>\r\n");
      out.write("                                            <i class=\"fas fa-school me-2\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <p class=\"card-text display-6\"\r\n");
      out.write("                                            style=\"font-weight: bold; text-shadow: 5px 5px 3px rgba(0, 0, 0, 0.5);\">\r\n");
      out.write("                                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalClassroom}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-12\">\r\n");
      out.write("                                <div\r\n");
      out.write("                                    style=\"background-color: white; box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.5); border-radius: 6px; margin-top: 24px;\">\r\n");
      out.write("                                    <div style=\"width: 600px; padding: 20px;\">\r\n");
      out.write("                                        <canvas id=\"barChart\"></canvas>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div\r\n");
      out.write("                            style=\"background-color: white; box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.5); border-radius: 6px; margin-top: 40px;\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-4\">\r\n");
      out.write("                                    <div style=\"width: 400px; padding: 20px 0px;\">\r\n");
      out.write("                                        <canvas id=\"userPieChart\"></canvas>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-4\">\r\n");
      out.write("                                    <div style=\"width: 400px; padding: 20px 0px;\">\r\n");
      out.write("                                        <canvas id=\"teacherClassroomPieChart\"></canvas>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-4\">\r\n");
      out.write("                                    <div style=\"width: 400px; padding: 20px 0px;\">\r\n");
      out.write("                                        <canvas id=\"studentClassroomPieChart\"></canvas>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        const ctx1 = document.getElementById('userPieChart').getContext('2d');\r\n");
      out.write("        const userPieChart = new Chart(ctx1, {\r\n");
      out.write("            type: 'pie',\r\n");
      out.write("            data: {\r\n");
      out.write("                labels: ['Sinh viên', 'Giáo viên'],\r\n");
      out.write("                datasets: [{\r\n");
      out.write("                    data: [");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write(',');
      out.write(' ');
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("], // Số lượng thực tế\r\n");
      out.write("                    backgroundColor: [\r\n");
      out.write("                        'rgba(54, 162, 235, 0.7)',  // Màu xanh dương\r\n");
      out.write("                        'rgba(255, 206, 86, 0.7)'   // Màu vàng\r\n");
      out.write("                    ],\r\n");
      out.write("                    borderColor: [\r\n");
      out.write("                        'rgba(54, 162, 235, 1)',\r\n");
      out.write("                        'rgba(255, 206, 86, 1)'\r\n");
      out.write("                    ],\r\n");
      out.write("                    borderWidth: 1,\r\n");
      out.write("                    hoverOffset: 30\r\n");
      out.write("                }]\r\n");
      out.write("            },\r\n");
      out.write("            options: {\r\n");
      out.write("                responsive: true,\r\n");
      out.write("                plugins: {\r\n");
      out.write("                    legend: {\r\n");
      out.write("                        position: 'bottom',\r\n");
      out.write("                        labels: {\r\n");
      out.write("                            font: {\r\n");
      out.write("                                size: 16\r\n");
      out.write("                            },\r\n");
      out.write("                            padding: 30\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("                    title: {\r\n");
      out.write("                        display: true,\r\n");
      out.write("                        text: 'Tỷ lệ Sinh viên và Giáo viên',\r\n");
      out.write("                        font: {\r\n");
      out.write("                            size: 20\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        const ctx2 = document.getElementById('teacherClassroomPieChart').getContext('2d');\r\n");
      out.write("        const teacherClassroomPieChart = new Chart(ctx2, {\r\n");
      out.write("            type: 'pie',\r\n");
      out.write("            data: {\r\n");
      out.write("                labels: ['Lớp học', 'Giáo viên'],\r\n");
      out.write("                datasets: [{\r\n");
      out.write("                    data: [");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write(',');
      out.write(' ');
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("],\r\n");
      out.write("                    backgroundColor: [\r\n");
      out.write("                        'rgba(126, 214, 165, 0.7)',\r\n");
      out.write("                        'rgba(248, 225, 108, 0.7)'\r\n");
      out.write("                    ],\r\n");
      out.write("                    borderColor: [\r\n");
      out.write("                        'rgba(126, 214, 165, 1)',\r\n");
      out.write("                        'rgba(248, 225, 108, 1)'\r\n");
      out.write("                    ],\r\n");
      out.write("                    borderWidth: 1,\r\n");
      out.write("                    hoverOffset: 30\r\n");
      out.write("                }]\r\n");
      out.write("            },\r\n");
      out.write("            options: {\r\n");
      out.write("                responsive: true,\r\n");
      out.write("                plugins: {\r\n");
      out.write("                    legend: {\r\n");
      out.write("                        position: 'bottom',\r\n");
      out.write("                        labels: {\r\n");
      out.write("                            font: {\r\n");
      out.write("                                size: 16\r\n");
      out.write("                            },\r\n");
      out.write("                            padding: 30\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("                    title: {\r\n");
      out.write("                        display: true,\r\n");
      out.write("                        text: 'Tỷ lệ Lớp học và Giáo viên',\r\n");
      out.write("                        font: {\r\n");
      out.write("                            size: 20\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        const ctx3 = document.getElementById('studentClassroomPieChart').getContext('2d');\r\n");
      out.write("        const studentClassroomPieChart = new Chart(ctx3, {\r\n");
      out.write("            type: 'pie',\r\n");
      out.write("            data: {\r\n");
      out.write("                labels: ['Lớp học', 'Sinh viên'],\r\n");
      out.write("                datasets: [{\r\n");
      out.write("                    data: [");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write(',');
      out.write(' ');
      if (_jspx_meth_c_005fout_005f5(_jspx_page_context))
        return;
      out.write("],\r\n");
      out.write("                    backgroundColor: [\r\n");
      out.write("                        'rgba(233, 78, 119, 0.7)',\r\n");
      out.write("                        'rgba(155, 89, 182, 0.7)'\r\n");
      out.write("                    ],\r\n");
      out.write("                    borderColor: [\r\n");
      out.write("                        'rgba(233, 78, 119, 1)',\r\n");
      out.write("                        'rgba(155, 89, 182, 1)'\r\n");
      out.write("                    ],\r\n");
      out.write("                    borderWidth: 1,\r\n");
      out.write("                    hoverOffset: 30\r\n");
      out.write("                }]\r\n");
      out.write("            },\r\n");
      out.write("            options: {\r\n");
      out.write("                responsive: true,\r\n");
      out.write("                plugins: {\r\n");
      out.write("                    legend: {\r\n");
      out.write("                        position: 'bottom',\r\n");
      out.write("                        labels: {\r\n");
      out.write("                            font: {\r\n");
      out.write("                                size: 16\r\n");
      out.write("                            },\r\n");
      out.write("                            padding: 30\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("                    title: {\r\n");
      out.write("                        display: true,\r\n");
      out.write("                        text: 'Tỷ lệ Lớp học và Sinh viên',\r\n");
      out.write("                        font: {\r\n");
      out.write("                            size: 20\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        const ctx4 = document.getElementById('barChart').getContext('2d');\r\n");
      out.write("        const barChart = new Chart(ctx4, {\r\n");
      out.write("            type: 'bar',\r\n");
      out.write("            data: {\r\n");
      out.write("                labels: ['Sinh viên', 'Giáo viên', 'Lớp học'],\r\n");
      out.write("                datasets: [{\r\n");
      out.write("                    label: 'Số lượng',\r\n");
      out.write("                    data: [\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fout_005f6(_jspx_page_context))
        return;
      out.write(",\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fout_005f7(_jspx_page_context))
        return;
      out.write(",\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fout_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    ],\r\n");
      out.write("                    backgroundColor: [\r\n");
      out.write("                        'rgba(54, 162, 235, 0.7)',\r\n");
      out.write("                        'rgba(255, 206, 86, 0.7)',\r\n");
      out.write("                        'rgba(126, 214, 165, 0.7)',\r\n");
      out.write("                    ],\r\n");
      out.write("                    borderColor: [\r\n");
      out.write("                        'rgba(54, 162, 235, 1)',\r\n");
      out.write("                        'rgba(255, 206, 86, 1)',\r\n");
      out.write("                        'rgba(126, 214, 165, 1)',\r\n");
      out.write("                    ],\r\n");
      out.write("                    borderWidth: 1,\r\n");
      out.write("                }]\r\n");
      out.write("            },\r\n");
      out.write("            options: {\r\n");
      out.write("                responsive: true,\r\n");
      out.write("                plugins: {\r\n");
      out.write("                    legend: {\r\n");
      out.write("                        display: false // ẩn legend vì chỉ có 1 dataset\r\n");
      out.write("                    },\r\n");
      out.write("                    title: {\r\n");
      out.write("                        display: true,\r\n");
      out.write("                        text: 'Thống kê tổng số Sinh viên, Giáo viên, Lớp học',\r\n");
      out.write("                        font: {\r\n");
      out.write("                            size: 20\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("                    tooltip: {\r\n");
      out.write("                        enabled: true\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                scales: {\r\n");
      out.write("                    y: {\r\n");
      out.write("                        beginAtZero: true,\r\n");
      out.write("                        ticks: {\r\n");
      out.write("                            stepSize: 1 // tăng giảm tùy dữ liệu của bạn\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /view/admin/dashboard.jsp(220,27) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalStudent}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent(null);
    // /view/admin/dashboard.jsp(220,62) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalTeacher}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f2.setParent(null);
    // /view/admin/dashboard.jsp(262,27) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalClassroom}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
    if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f3.setParent(null);
    // /view/admin/dashboard.jsp(262,64) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalTeacher}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
    if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f4.setParent(null);
    // /view/admin/dashboard.jsp(304,27) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalClassroom}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
    if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f5.setParent(null);
    // /view/admin/dashboard.jsp(304,64) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalStudent}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
    if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f6.setParent(null);
    // /view/admin/dashboard.jsp(348,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f6.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalStudent}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f6 = _jspx_th_c_005fout_005f6.doStartTag();
    if (_jspx_th_c_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f7.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f7.setParent(null);
    // /view/admin/dashboard.jsp(349,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalTeacher}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f7 = _jspx_th_c_005fout_005f7.doStartTag();
    if (_jspx_th_c_005fout_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f7);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f8 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f8.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f8.setParent(null);
    // /view/admin/dashboard.jsp(350,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f8.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalClassroom}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f8 = _jspx_th_c_005fout_005f8.doStartTag();
    if (_jspx_th_c_005fout_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f8);
    return false;
  }
}
