/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-09-11 08:25:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class student_005fclassroom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1746088531666L));
    _jspx_dependants.put("jar:file:/D:/study/code/javaProgramming/javaWebServletBackup/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SICT-portal/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098736290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Hệ thống quản lý trường SICT</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- Sidebar -->\r\n");
      out.write("            <div class=\"col-md-2 sidebar p-0\">\r\n");
      out.write("                <div class=\"text-left p-3 bg-dark\">\r\n");
      out.write("                    <div class=\"logo\">SICT<span class=\"sub\"> Portal</span></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"nav flex-column\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"dashboard\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-tachometer-alt me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Dashboard\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"accountList\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-users me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Tài khoản người dùng\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"studentList\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-user-graduate me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Thông tin sinh viên\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"teacherList\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-chalkboard-teacher me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Thông tin giáo viên\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"classroomList\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-school me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Thông tin lớp học\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item active\">\r\n");
      out.write("                        <span class=\"active__subItem\"></span>\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"classroomList\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-user-plus me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Sinh viên - Lớp học\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item mt-3\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"logout\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-sign-out-alt me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Đăng xuất\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Main content -->\r\n");
      out.write("            <div class=\"col-md-10 main-content\">\r\n");
      out.write("                <div class=\"tab-content\">\r\n");
      out.write("                    <!-- Student - Classroom Tab -->\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <h2 class=\"mb-4\">Sinh viên - Lớp học</h2>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <form method=\"get\" action=\"admin\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"action\" value=\"searchStudentListByClassroomID\" />\r\n");
      out.write("                                    <label for=\"classroomID\" class=\"form-label\">Xem danh sách sinh viên theo mã\r\n");
      out.write("                                        lớp</label>\r\n");
      out.write("                                    <div class=\"input-group\" style=\"box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.5); border-radius: 6px;\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"classroomID\" name=\"classroomID\"\r\n");
      out.write("                                            style=\"box-shadow: none;\" placeholder=\"Nhập mã lớp...\">\r\n");
      out.write("                                        <button class=\"btn btn-primary\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <form method=\"get\" action=\"admin\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"action\" value=\"searchClassroomListByStudentID\" />\r\n");
      out.write("                                    <label for=\"studentID\" class=\"form-label\">Xem danh sách lớp theo mã sinh viên</label>\r\n");
      out.write("                                    <div class=\"input-group\" style=\"box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.5); border-radius: 6px;\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"studentID\" name=\"studentID\"\r\n");
      out.write("                                            style=\"box-shadow: none;\" placeholder=\"Nhập mã sinh viên...\">\r\n");
      out.write("                                        <button class=\"btn btn-primary\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\" style=\"border-top: 1px solid black; margin-top: 24px;\">\r\n");
      out.write("                            <div class=\"col-md-6\" style=\"margin-top: 24px;\">\r\n");
      out.write("                                <form method=\"post\" action=\"admin\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"action\" value=\"addStudent_classroom\" />\r\n");
      out.write("                                    <label style=\"font-size: 18.72px; font-weight: bold;\" for=\"classroomID\"\r\n");
      out.write("                                        class=\"form-label text-center w-100\">\r\n");
      out.write("                                        Thêm sinh viên vào lớp\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <div class=\"input-group\" style=\"box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.5); border-radius: 6px;\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"classroomID\" name=\"classroomID\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${classroomID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"box-shadow: none;\"\r\n");
      out.write("                                            placeholder=\"Nhập mã lớp...\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"studentID\" name=\"studentID\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studentID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"box-shadow: none;\" placeholder=\"Nhập mã SV...\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"d-flex justify-content-end\" style=\"margin-top: 16px;\">\r\n");
      out.write("                                        <button type=\"submit\" class=\"btn btn-success btn-sm\">\r\n");
      out.write("                                            <i class=\"fas fa-user-plus\"></i> Thêm sinh viên\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6\" style=\"margin-top: 24px;\">\r\n");
      out.write("                                <form method=\"post\" action=\"admin\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"action\" value=\"deleteStudent_classroom\" />\r\n");
      out.write("                                    <label style=\"font-size: 18.72px; font-weight: bold\" for=\"studentID\"\r\n");
      out.write("                                        class=\"form-label text-center w-100\">\r\n");
      out.write("                                        Xóa sinh viên khỏi lớp\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <div class=\"input-group\" style=\"box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.5); border-radius: 6px;\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"studentID\" name=\"studentID\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studentID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"box-shadow: none;\" placeholder=\"Nhập mã SV...\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"classroomID\" name=\"classroomID\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${classroomID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"box-shadow: none;\"\r\n");
      out.write("                                            placeholder=\"Nhập mã lớp...\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"d-flex justify-content-end\" style=\"margin-top: 16px;\">\r\n");
      out.write("                                        <button type=\"submit\" class=\"btn btn-danger btn-sm\">\r\n");
      out.write("                                            <i class=\"fas fa-user-minus\"></i> Xoá sinh viên\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /view/admin/student_classroom.jsp(17,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty message}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("        <div class=\"alert-error\">\r\n");
        out.write("            &#9888; ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("        </div>\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /view/admin/student_classroom.jsp(22,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty succeedAddMessage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("        <div class=\"alert-success\">\r\n");
        out.write("            &#9989; ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${succeedAddMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("        </div>\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /view/admin/student_classroom.jsp(27,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty succeedDeleteMessage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("        <div class=\"alert-success\">\r\n");
        out.write("            &#9989; ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${succeedDeleteMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("        </div>\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }
}
