/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-09-11 08:24:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class updateAccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1746088531666L));
    _jspx_dependants.put("jar:file:/D:/study/code/javaProgramming/javaWebServletBackup/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SICT-portal/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098736290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Hệ thống quản lý trường SICT</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- Sidebar -->\r\n");
      out.write("            <div class=\"col-md-2 sidebar p-0\">\r\n");
      out.write("                <div class=\"text-left p-3 bg-dark\">\r\n");
      out.write("                    <div class=\"logo\">SICT<span class=\"sub\"> Portal</span></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"nav flex-column\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"dashboard\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-tachometer-alt me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Dashboard\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item active\">\r\n");
      out.write("                        <span class=\"active__subItem\"></span>\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"accountList\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-users me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Tài khoản người dùng\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"studentList\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-user-graduate me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Thông tin sinh viên\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"teacherList\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-chalkboard-teacher me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Thông tin giáo viên\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"classroomList\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-school me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Thông tin lớp học\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"student_classroom\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-user-plus me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Sinh viên - Lớp học\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item mt-3\">\r\n");
      out.write("                        <form method=\"get\" action=\"admin\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"logout\">\r\n");
      out.write("                            <button type=\"submit\" class=\"sidebar-btn\">\r\n");
      out.write("                                <div class=\"sidebar__icon-container\">\r\n");
      out.write("                                    <i class=\"fas fa-sign-out-alt me-2\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                Đăng xuất\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Main content -->\r\n");
      out.write("            <div class=\"col-md-10 main-content\">\r\n");
      out.write("                <div class=\"tab-content\">\r\n");
      out.write("                    <!-- Students Tab -->\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("                            <h2>Quản lý thông tin tài khoản</h2>\r\n");
      out.write("                            <div class=\"export-btn__container\">\r\n");
      out.write("                                <form method=\"get\" action=\"admin\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"action\" value=\"exportAccounts\" />\r\n");
      out.write("                                    <button type=\"submit\" class=\"export-btn\">\r\n");
      out.write("                                        <i class=\"fa-solid fa-file-arrow-down\"></i> Xuất Excel\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <form method=\"get\" action=\"admin\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"action\" value=\"addAccountForm\" />\r\n");
      out.write("                                <button class=\"btn btn-primary\" type=\"submit\">\r\n");
      out.write("                                    <i class=\"fas fa-plus me-1\"></i>\r\n");
      out.write("                                    Thêm tài khoản\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-header d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                <span>Danh sách tài khoản</span>\r\n");
      out.write("                                <div style=\"margin: 0px 30px 0px auto;\">\r\n");
      out.write("                                    <span style=\"margin-right: 5px; font-weight: normal;\">\r\n");
      out.write("                                        Xóa tài khoản đã chọn\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <button type=\"button\" id=\"deleteTriggerBtn\" class=\"btn btn-outline-secondary\">\r\n");
      out.write("                                        <i class=\"fas fa-trash\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"filter-controls\" style=\"margin-right: 30px;\">\r\n");
      out.write("                                    <span style=\"margin-right: 5px; font-weight: normal;\" class=\"filter-controls__text\">\r\n");
      out.write("                                        Bộ lọc\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <button class=\"btn btn-outline-secondary\" id=\"filterBtn\">\r\n");
      out.write("                                        <i class=\"fa-solid fa-filter\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <form method=\"get\" action=\"admin\">\r\n");
      out.write("                                    <div style=\"display: flex;\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"action\" value=\"searchAccount\" />\r\n");
      out.write("                                        <input\r\n");
      out.write("                                            style=\"outline: none; border: none; border-bottom-left-radius: 6px; border-top-left-radius: 6px; padding-left: 10px;\"\r\n");
      out.write("                                            type=\"text\" name=\"accountID\" placeholder=\"Nhập mã tài khoản...\" required />\r\n");
      out.write("                                        <button class=\"btn btn-outline-secondary\" type=\"submit\">\r\n");
      out.write("                                            <i class=\"fas fa-search\"></i>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <div class=\"table-responsive\">\r\n");
      out.write("                                    <div style=\"max-height: 520.5px; overflow: auto;\">\r\n");
      out.write("                                        <form method=\"post\" action=\"admin\">\r\n");
      out.write("                                            <input type=\"hidden\" name=\"action\" value=\"deleteAccounts\">\r\n");
      out.write("                                            <input type=\"hidden\" id=\"randomCodeInput\" name=\"randomCode\">\r\n");
      out.write("                                            <input type=\"hidden\" id=\"deleteCodeConfirm\" name=\"deleteCodeConfirm\">\r\n");
      out.write("                                            <table class=\"table table-striped table-hover\">\r\n");
      out.write("                                                <thead>\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                        <th><input type=\"checkbox\" id=\"checkAll\" onclick=\"toggle(this)\">\r\n");
      out.write("                                                        </th>\r\n");
      out.write("                                                        <th>STT</th>\r\n");
      out.write("                                                        <th>Mã tài khoản</th>\r\n");
      out.write("                                                        <th>Tên tài khoản</th>\r\n");
      out.write("                                                        <th>Mật khẩu</th>\r\n");
      out.write("                                                        <th>Quyền đăng nhập</th>\r\n");
      out.write("                                                        <th>Mã SV</th>\r\n");
      out.write("                                                        <th>Hành động</th>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                </thead>\r\n");
      out.write("                                                <tbody>\r\n");
      out.write("                                                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                                </tbody>\r\n");
      out.write("                                            </table>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <button id=\"submitDeleteBtn\" style=\"display: none;\"\r\n");
      out.write("                                            type=\"submit\"></button>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    ");

                                        int groupSize = 5;
                                        int currentPage = (Integer) request.getAttribute("currentPage");
                                        int totalPages = (Integer) request.getAttribute("totalPages");

                                        int groupStart = ((currentPage - 1) / groupSize) * groupSize + 1;
                                        int groupEnd = Math.min(groupStart + groupSize - 1, totalPages);
                                    
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                                    <div class=\"pagination\">\r\n");
      out.write("                                        <!-- Nút về trang đầu -->\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                                        <!-- Nút Prev -->\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                                        <!-- Các trang trong nhóm -->\r\n");
      out.write("                                        ");

                                            int notCurrentPageCnt = -1;
                                            for (int i = groupStart; i <= groupEnd; i++) {
                                                notCurrentPageCnt++;
                                        
      out.write("\r\n");
      out.write("                                            <a href=\"admin?action=accountList&page=");
      out.print(i);
      out.write("\"\r\n");
      out.write("                                            class=\"");
      out.print( (i == currentPage) ? "current" : "notCurrentPage" + notCurrentPageCnt );
      out.write("\">\r\n");
      out.write("                                                ");
      out.print(i);
      out.write("\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        ");

                                            }
                                        
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                                        <!-- Nút Next -->\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \r\n");
      out.write("                                        <!-- Nút tới trang cuối -->\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Edit Account Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"editAccountModal\" tabindex=\"-1\" aria-labelledby=\"editAccountModalLabel\"\r\n");
      out.write("        aria-hidden=\"true\" style=\"position: fixed; top: 10%;\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\">Chỉnh sửa thông tin tài khoản <strong>\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </strong></h5>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    <form action=\"admin\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"updateAccount\" />\r\n");
      out.write("                        <input type=\"hidden\" name=\"accountID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account.accountID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"studentID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account.studentID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"role\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account.role}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"username\" class=\"form-label\">Tên TK</label>\r\n");
      out.write("                            <input id=\"username\" class=\"form-control\" type=\"text\" name=\"username\"\r\n");
      out.write("                                value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"password\" class=\"form-label\">Mật khẩu</label>\r\n");
      out.write("                            <input id=\"password\" class=\"form-control\" type=\"text\" name=\"password\"\r\n");
      out.write("                                value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div style=\"display: flex; flex-direction: row-reverse;\">\r\n");
      out.write("                            <button style=\"margin-left: 10px;\" type=\"submit\" class=\"btn btn-primary\">Lưu</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Hủy</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        window.addEventListener('DOMContentLoaded', (event) => {\r\n");
      out.write("            var myModal = new bootstrap.Modal(document.getElementById('editAccountModal'));\r\n");
      out.write("            myModal.show();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        function toggleStudentIDField() {\r\n");
      out.write("            const roleSelect = document.getElementById(\"role\");\r\n");
      out.write("            const studentIDField = document.getElementById(\"studentIDField\");\r\n");
      out.write("            const studentIDInput = document.getElementById(\"studentID\");\r\n");
      out.write("\r\n");
      out.write("            if (roleSelect.value === \"student\") {\r\n");
      out.write("                studentIDField.style.display = \"block\";\r\n");
      out.write("                studentIDInput.required = true;\r\n");
      out.write("            } else {\r\n");
      out.write("                studentIDField.style.display = \"none\";\r\n");
      out.write("                studentIDInput.value = \"\";\r\n");
      out.write("                studentIDInput.required = false;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("            const roleSelect = document.getElementById(\"role\");\r\n");
      out.write("\r\n");
      out.write("            // Gọi hàm ban đầu để thiết lập trạng thái đúng\r\n");
      out.write("            toggleStudentIDField();\r\n");
      out.write("\r\n");
      out.write("            // Lắng nghe sự kiện khi thay đổi lựa chọn\r\n");
      out.write("            roleSelect.addEventListener(\"change\", toggleStudentIDField);\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    <div style=\"cursor: pointer;\" id=\"overlay\" class=\"filter-overlay\"></div>\r\n");
      out.write("    <div id=\"filterModal\" class=\"filter-modal\">\r\n");
      out.write("        <h3>Bộ lọc tài khoản</h3>\r\n");
      out.write("        <form action=\"admin\" method=\"get\">\r\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"accountFilter\" />\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"role\" class=\"form-label\">Quyền đăng nhập</label>\r\n");
      out.write("                <select class=\"form-select\" id=\"role\" name=\"role\">\r\n");
      out.write("                    <option value=\"\">Chọn quyền đăng nhập</option>\r\n");
      out.write("                    <option value=\"student\">Student</option>\r\n");
      out.write("                    <option value=\"admin\">Admin</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"display: flex; flex-direction: row-reverse;\">\r\n");
      out.write("                <button style=\"margin-left: 10px;\" type=\"submit\" class=\"btn btn-primary\">Lưu</button>\r\n");
      out.write("                <button id=\"cancel-filter__btn\" type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("                    data-bs-dismiss=\"modal\">Hủy</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        const filterBtn = document.getElementById('filterBtn');\r\n");
      out.write("        const filterModal = document.getElementById('filterModal');\r\n");
      out.write("        const overlay = document.getElementById('overlay');\r\n");
      out.write("        const cancelFilter__btn = document.getElementById('cancel-filter__btn');\r\n");
      out.write("\r\n");
      out.write("        filterBtn.addEventListener('click', () => {\r\n");
      out.write("            filterModal.style.display = 'block';\r\n");
      out.write("            overlay.style.display = 'block';\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        overlay.addEventListener('click', () => {\r\n");
      out.write("            filterModal.style.display = 'none';\r\n");
      out.write("            overlay.style.display = 'none';\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        cancelFilter__btn.addEventListener('click', () => {\r\n");
      out.write("            filterModal.style.display = 'none';\r\n");
      out.write("            overlay.style.display = 'none';\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("        function toggle(source) {\r\n");
      out.write("            checkboxes = document.getElementsByName('accountIds');\r\n");
      out.write("            for (var i = 0; i < checkboxes.length; i++) {\r\n");
      out.write("                checkboxes[i].checked = source.checked;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("        <div class=\"modal fade\" id=\"deleteAccountsModal\" tabindex=\"-1\" aria-labelledby=\"deleteAccountsModalLabel\"\r\n");
      out.write("        aria-hidden=\"true\" style=\"position: fixed; top: 10%;\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header bg-danger text-white\">\r\n");
      out.write("                    <h5 class=\"modal-title\">Xóa tài khoản</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\" style=\"display: flex; flex-direction: column;\">\r\n");
      out.write("                    <p>Nhập lại mã sau để xác nhận xóa:\r\n");
      out.write("                        <strong id=\"randomCode\"></strong>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <input style=\"border-radius: 5px; border: 1px solid rgba(0, 0, 0, 0.3); margin-bottom: 15px; outline: none; padding: 5px 0px 5px 10px;\" type=\"text\" id=\"deleteCodeConfirmInput\" placeholder=\"Nhập mã xác nhận\" required />\r\n");
      out.write("                    <p class=\"text-danger\">Hành động này không thể hoàn tác!</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Hủy</button>\r\n");
      out.write("                    <button id=\"deleteTriggerBtn2\" class=\"btn btn-danger\">Xóa</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        document.getElementById(\"deleteTriggerBtn\").addEventListener(\"click\", function () {\r\n");
      out.write("            var myModal = new bootstrap.Modal(document.getElementById('deleteAccountsModal'));\r\n");
      out.write("            myModal.show();\r\n");
      out.write("            showDeleteConfirm();\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("        document.getElementById(\"deleteTriggerBtn2\").addEventListener(\"click\", function () {\r\n");
      out.write("            document.getElementById(\"deleteCodeConfirm\").value = document.getElementById(\"deleteCodeConfirmInput\").value;\r\n");
      out.write("            document.getElementById(\"submitDeleteBtn\").click();\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("        let generatedCode = \"\";\r\n");
      out.write("\r\n");
      out.write("        function generateRandomCode(length = 6) {\r\n");
      out.write("            const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';\r\n");
      out.write("            let code = '';\r\n");
      out.write("            for (let i = 0; i < length; i++) {\r\n");
      out.write("                code += chars.charAt(Math.floor(Math.random() * chars.length));\r\n");
      out.write("            }\r\n");
      out.write("            return code;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function showDeleteConfirm() {\r\n");
      out.write("            generatedCode = generateRandomCode();\r\n");
      out.write("            document.getElementById(\"randomCode\").textContent = generatedCode;\r\n");
      out.write("            document.getElementById(\"randomCodeInput\").value = generatedCode;\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /view/admin/updateAccount.jsp(181,52) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("a");
    // /view/admin/updateAccount.jsp(181,52) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accountList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /view/admin/updateAccount.jsp(181,52) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("loop");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                                        <tr>\r\n");
          out.write("                                                            <td><input type=\"checkbox\" name=\"accountIds\"\r\n");
          out.write("                                                                    value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.accountID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"></td>\r\n");
          out.write("                                                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.index + 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                                                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.accountID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                                                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                                                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                                                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.role}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                                                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.studentID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                                                            <td>\r\n");
          out.write("                                                                <div style=\"display: flex; gap: 5px;\">\r\n");
          out.write("                                                                    <a class=\"btn btn-sm btn-warning\"\r\n");
          out.write("                                                                        href=\"admin?action=updateAccountForm&accountID=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.accountID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                                                        <i class=\"fas fa-edit\"></i>\r\n");
          out.write("                                                                    </a>\r\n");
          out.write("                                                                    <a class=\"btn btn-sm btn-danger\"\r\n");
          out.write("                                                                        href=\"admin?action=deleteAccountForm&accountID=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.accountID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                                                        <i class=\"fas fa-trash\"></i>\r\n");
          out.write("                                                                    </a>\r\n");
          out.write("                                                                </div>\r\n");
          out.write("                                                            </td>\r\n");
          out.write("                                                        </tr>\r\n");
          out.write("                                                    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /view/admin/updateAccount.jsp(223,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage > 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                            <a class=\"firstPageBtn\" href=\"admin?action=accountList&page=1\">« First</a>\r\n");
        out.write("                                        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /view/admin/updateAccount.jsp(228,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage > 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                            <a class=\"PrevPageBtn\" href=\"admin?action=accountList&page=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage - 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">‹\r\n");
        out.write("                                                Prev</a>\r\n");
        out.write("                                        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /view/admin/updateAccount.jsp(248,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage < totalPages}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                            <a class=\"nextPageBtn\"\r\n");
        out.write("                                                href=\"admin?action=accountList&page=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage + 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">Next\r\n");
        out.write("                                                ›</a>\r\n");
        out.write("                                        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /view/admin/updateAccount.jsp(255,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage < totalPages}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                            <a class=\"lastPageBtn\" href=\"admin?action=accountList&page=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPages}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">Last\r\n");
        out.write("                                                »</a>\r\n");
        out.write("                                        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /view/admin/updateAccount.jsp(275,28) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account.accountID}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f4.setParent(null);
    // /view/admin/updateAccount.jsp(280,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty message}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
    if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                        <div class=\"alert-error\">\r\n");
        out.write("                            &#9888; ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("                        </div>\r\n");
        out.write("                    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    return false;
  }
}
